#!/usr/bin/env python

# Medusa simple web-output daemon

from daemon import Daemon
import os
import sys
import time

INST_PATH = "/home/sulami/medusa/mswo/"
RENDER_INTERVAL = 300
IN_PATH = "/home/sulami/medusa.out"
OUT_PATH = "/home/sulami/mswo.html"

def readtxt():
    try:
        with outtxt as open(IN_PATH, mode='r'):
            

"""
# Generic Unix daemon code, courtesy of Sander Marechal, http://www.jejik.com/articles/2007/02/a_simple_unix_linux_daemon_in_python/
class MyDaemon(Daemon):
    def run(self):
        while True:
            read_services(read_peers())
            time.sleep(CHECK_INTERVAL)

if __name__ == "__main__":
    daemon = MyDaemon('/tmp/medusa-master.pid')
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            write_log("Daemon started")
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
            write_log("Daemon stopped")
        elif 'restart' == sys.argv[1]:
            daemon.restart()
            write_log("Daemon restarted")
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start|stop|restart" % sys.argv[0]
        sys.exit(2)
"""
